### ISSUE TITLE
What is the bootloader program and how did you generate 10-monitor.conf?

### ISSUE THREAD

**Issue by Goosegit11** [chent7/dotfiles-root#1]
You have both 10-monitor.conf and this:
 https://github.com/chent7/dotfiles/blob/master/vg259qm-vg279qm.txt
 
Why?

**Comment by chent7** [comment]
That's just a text file in case I forget how to set it in xrandr.

Files in /boot/loader are configs for systemd-boot.

**Comment by Goosegit11** [comment]
Got it, thanks.
